sudo: required

services:
  - docker

language: go

before_install:
  - openssl aes-256-cbc -K $encrypted_98ed7a1d9a8c_key -iv $encrypted_98ed7a1d9a8c_iv
    -in gce.json.enc -out gce.json -d

deploy:
  provider: gae
  keyfile: gce.json
  project: hellogo-147901
  on: master
  verbosity: debug
