sudo: required

services:
  - docker

language: go

before_install:
  - openssl aes-256-cbc -K $encrypted_7748a1005700_key -iv $encrypted_7748a1005700_iv
    -in gce.json.enc -out gce.json -d

deploy:
  provider: gae
  keyfile: gce.json
  project: hellogo
  on: master
